- .github/workflows/create-jira-issue.yml
- src/styles/font.css
- src/styles/globals.css
> #1
> 공통 CSS 작성 했습니다. 색상, 폰트 버튼, 태그, input
아래의 이미지 대로 작성했습니다. 참고부탁드립니다.
> 확인부탁드립니당..
> [EA3-82] feature: 공통 CSS 작성

- src/app/(common)/study/[id]/study-community/write/page.tsx
> 💄 Style: 스터디 커뮤니티 페이지 추가

- src/components/study/TimeGrid.tsx
> 🐛 Fix: 변수 수정

- src/components/common/calendar/CalendarWrite.tsx
- src/components/study-room/management/StudyMemberList.tsx
- src/components/study-room/management/StudyRoomInviteModal.tsx
> 🐛 Fix : 오류수정

- src/components/common/calendar/CalendarSmallDetailItem.tsx
> 🐛 Fix : 타입 수정

- src/components/main/MainStudyList.tsx
> 🐛 Fix: props 수정

- src/app/(common)/(main)/page.tsx
> 🐛 Fix : Suspense 추가

- package.json
- src/app/layout.tsx
- src/components/recruitment/RecruitmentDetailPage.tsx
- src/components/study/CreateStudyModal.tsx
#55 
토스트 메세지 추가
토스트 메세지 사용할 곳에
import { toast } from 'react-toastify';
toast.success('스터디 생성이 완료되었습니다!');
이런 식으로 넣어주시면 되고 Toast 메세지 폰트나 색 변경 원하시면 최상위 layoyt.tsx에서 수정해주시면 됩니다! 아래 링크 참고해주세요!
[React-toastify](https://fkhadra.github.io/react-toastify/introduction/)
> ✨ Feat: Toast 메세지 추가

- src/components/my/RecruitmentCard.tsx
- src/components/my/StudyCard.tsx
- src/styles/globals.css
- RecruifmentCard.tsx 포맷팅
- StudyCard.tsx 스터디 이미지 크기
> 🐛 Fix : 포맷팅, 이미지 크기 수정

- src/components/study/ListMenuStudy.tsx
- src/components/study/ScheduleTooltip.tsx
- src/components/study/SetPeriodModal.tsx
- src/components/study/StudyScheduleClient.tsx
- src/components/study/SubmitScheduleModal.tsx
> 🐛 Fix: lucide 아이콘 ssr false로 수정

- src/components/common/calendar/CalendarBigDetail.tsx
- src/components/common/calendar/CalendarBigDetailItem.tsx
- src/components/common/calendar/CalendarBigShell.tsx
- src/components/common/calendar/CalendarSmallDetail.tsx
- src/components/common/calendar/CalendarWrite.tsx
- src/components/main/MainPagination.tsx
- src/components/main/MainRecruitmentList.tsx
- src/components/main/MainStudyList.tsx
- src/components/manager/ManagerHeader.tsx
- src/components/manager/ManagerPagination.tsx
- src/components/manager/ManagerRecruitmentsPage.tsx
- src/components/manager/ManagerStudiesPage.tsx
- src/components/manager/ManagerUsersPage.tsx
- src/components/study-room/chat/ChatDate.tsx
- src/components/study-room/dashboard/StudyDashboardPage.tsx
- src/components/study-room/dashboard/StudyDashboardSkeleton.tsx
- src/components/study-room/dashboard/StudyInfoCard.tsx
- src/components/study-room/management/StudyMemberCard.tsx
- src/components/study-room/management/StudyRoomExtendWrite.tsx
- src/components/study-room/management/StudyRoomInfo.tsx
- src/components/study-room/management/StudyRoomInfoWrite.tsx
- src/components/study-room/management/StudyRoomInviteModal.tsx
- src/components/study-room/sideMenu/SideMenuItem.tsx
- src/components/study-room/sideMenu/SideStudyInfo.tsx
> Fix : 루시드 아이콘 다이나믹 임포트

- src/components/profile/pr/EditPrClient.tsx
> [Fix] 루시드 아이콘 임포트 수정

- src/components/recruitment/RecruitmentWritePage.tsx
- src/components/study-room/sideMenu/SideMenuItem.tsx
- src/components/study/CreateStudyModal.tsx
- src/components/study/StudyCommunityWritePage.tsx
- src/types/study.d.ts
#55 
🐛 Fix: 스터디 생성 시 서브헤더에 반영되도록 수정
> 🐛 Fix: 스터디 생성 시 서브헤더에 반영되도록 수정

- src/components/main/MainPage.tsx
- src/components/main/MainRecruitmentList.tsx
- src/components/main/MainStudyList.tsx
- src/components/manager/ManagerRecruitmentsPage.tsx
- src/components/manager/ManagerStudiesPage.tsx
- src/components/manager/ManagerUsersPage.tsx
- src/components/my/StudyCard.tsx
- src/components/study-room/dashboard/StudyAttendance.tsx
- src/components/study-room/management/StudyDelete.tsx
- src/components/study-room/management/StudyRoomExtendWrite.tsx
- src/components/study-room/management/StudyRoomInfoWrite.tsx
> 🐛 Fix : 모집글 작성 버튼 위치 수정

- src/components/main/MainPage.tsx
- src/components/study/StudyCommunityClient.tsx
- 모집글 제목 변경
- 스터디커뮤니티 작성 버튼 진행중인 스터디에만 나타나게 수정
> 🐛 Fix :  모집글 제목 변경, 스터디커뮤니티 작성 버튼 진행중인 스터디에만 나타나게 수정

- src/components/auth/CallbackClient.tsx
- src/components/common/Header.tsx
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
소셜 로그인 쿠키 설정
>
> 🐛 Fix: 소셜 로그인 쿠키 설정

- src/components/common/calendar/CalendarSmallDetail.tsx
- src/components/main/MainRecruitmentList.tsx
- src/components/manager/ManagerHeader.tsx
- src/components/manager/ManagerRecruitmentsPage.tsx
- src/components/manager/ManagerStudiesPage.tsx
- src/components/manager/ManagerUsersPage.tsx
- src/components/study-room/dashboard/StudyAttendance.tsx
- src/components/study-room/dashboard/StudyPostItem.tsx
> 🐛 Fix : 출석 화면 날짜 누락 수정

- src/components/study-room/dashboard/StudyAttendance.tsx
시간포맷이 00:00:00 로 되어 있어서 마지막 날짜 누락 됨 -> 23:59:59로 변경
> 🐛 Fix : 출석 기간 표시 날짜 포맷 재수정

- src/components/main/MainRecruitmentList.tsx
- src/components/manager/ManagerRecruitmentsPage.tsx
- src/components/manager/ManagerStudiesPage.tsx
- src/components/manager/ManagerUsersPage.tsx
- 관리자 유저, 스터디, 모집글 검색 로직 변경
- 메인 모집글 목록 검색 로직 변경
> Fix : 관리자, 모집글 페이징 로직 변경

- src/components/common/Comment.tsx
- src/components/common/Pagination2.tsx
- src/components/common/WriteComment.tsx
- src/components/recruitment/RecruitmentDetailPage.tsx
- src/components/recruitment/RecruitmentWritePage.tsx
- src/components/study/StudyCommunityDetailPage.tsx
- src/components/study/StudyCommunityWritePage.tsx
> 🐛 Fix: 모집글 신청내역 페이지네이션 수정

- src/components/profile/EditProfileCient.tsx
- src/components/profile/pr/FeedbackModal.tsx
- src/components/profile/pr/FeedbackSection.tsx
- src/components/study/ChatClient.tsx
> [Fix] 기본 프로필 이미지 수정

- src/components/common/NotificationModal.tsx
> [Fix] 알림 정렬 수정

- src/components/auth/LoginClient.tsx
- src/components/auth/SignupClient.tsx
- src/components/profile/PasswordChangeModal.tsx
- src/components/profile/WithdrawalClient.tsx
> [Style] 비밀번호 입력창에 보기/숨기기 아이콘 추가

- src/components/common/ClickVerticalMenu.tsx
- src/components/recruitment/RecruitmentDetailPage.tsx
- src/components/recruitment/RecruitmentModifyPage.tsx
- src/components/recruitment/RecruitmentWritePage.tsx
- src/components/study/CreateStudyModal.tsx
- src/components/study/StudyCommunityDetailPage.tsx
- src/components/study/StudyCommunityModifyPage.tsx
- src/components/study/StudyCommunityWritePage.tsx
> 🐛 Fix: 스터디 모집글 수정 오류 수정

- src/components/recruitment/RecruitmentDetailPage.tsx
> 💄 Style: 로딩 스피너 추가

- src/components/profile/WithdrawalClient.tsx
> [Fix] 회원 탈퇴 수정

- next.config.ts
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
새 이미지 도메인 주소 추가
>
> 🐛 Fix: 새 이미지 도메인 주소 추가

- src/components/my/ApplicationListClient.tsx
- src/components/my/ApplyingStudyCard.tsx
- src/types/my.ts
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
라우터 수정
>
> 🐛 Fix: 라우터 수정

- src/components/study-room/dashboard/StudyAttendance.tsx
> 🐛 Fix: 색상 수정

- src/components/common/WriteComment.tsx
- src/components/recruitment/RecruitmentDetailPage.tsx
- src/components/recruitment/RecruitmentDetailSkeleton.tsx
- src/components/recruitment/RecruitmentFormSkeleton.tsx
- src/components/recruitment/RecruitmentModifyPage.tsx
- src/components/recruitment/RecruitmentModifySkeleton.tsx
- src/components/recruitment/RecruitmentWritePage.tsx
- src/components/study/CreateStudyModal.tsx
- src/components/study/StudyCommunityModifyPage.tsx
- src/components/study/StudyCommunityWritePage.tsx
- src/components/study/StudyPostDetailSkeleton.tsx
- src/styles/font.css
- src/styles/globals.css
> 💄 Style: 반응형 디자인 수정
